package com.calorietracker.service;

import java.util.List;

import com.calorietracker.entity.IngredientCategory;

public final class GlobalFoodDataset {

    private GlobalFoodDataset() {
    }

    public record IngredientSeed(
        String name,
        IngredientCategory category,
        String cuisine,
        double caloriesPer100g,
        String servingNote
    ) {
    }

    public record DishComponentSeed(String ingredientName, double grams) {
    }

    public record DishSeed(String name, String cuisine, String description, List<DishComponentSeed> components) {
    }

    public static List<IngredientSeed> ingredients() {
        return List.of(
            i("Apple", IngredientCategory.FRUIT, "Global", 52, "1 medium apple"),
            i("Banana", IngredientCategory.FRUIT, "Global", 89, "1 medium banana"),
            i("Orange", IngredientCategory.FRUIT, "Mediterranean", 47, "1 medium orange"),
            i("Mango", IngredientCategory.FRUIT, "India", 60, "1 cup diced"),
            i("Pineapple", IngredientCategory.FRUIT, "Tropical", 50, "1 cup chunks"),
            i("Papaya", IngredientCategory.FRUIT, "Southeast Asia", 43, "1 cup diced"),
            i("Guava", IngredientCategory.FRUIT, "Latin America", 68, "1 fruit"),
            i("Dragon Fruit", IngredientCategory.FRUIT, "Southeast Asia", 57, "1 cup"),
            i("Lychee", IngredientCategory.FRUIT, "China", 66, "10 fruits"),
            i("Dates", IngredientCategory.FRUIT, "Middle Eastern", 282, "5 dates"),
            i("Fig Fresh", IngredientCategory.FRUIT, "Mediterranean", 74, "2 figs"),
            i("Pomegranate", IngredientCategory.FRUIT, "Middle Eastern", 83, "1 cup seeds"),
            i("Grapes", IngredientCategory.FRUIT, "Global", 69, "1 cup"),
            i("Blueberries", IngredientCategory.FRUIT, "North American", 57, "1 cup"),
            i("Strawberries", IngredientCategory.FRUIT, "Global", 32, "1 cup"),
            i("Kiwi", IngredientCategory.FRUIT, "New Zealand", 61, "2 kiwis"),
            i("Peach", IngredientCategory.FRUIT, "Global", 39, "1 peach"),
            i("Pear", IngredientCategory.FRUIT, "Global", 57, "1 pear"),
            i("Watermelon", IngredientCategory.FRUIT, "Global", 30, "1 cup"),
            i("Cantaloupe", IngredientCategory.FRUIT, "Global", 34, "1 cup"),
            i("Coconut Flesh", IngredientCategory.FRUIT, "Tropical", 354, "1 cup shredded"),
            i("Avocado", IngredientCategory.FRUIT, "Latin America", 160, "half avocado"),
            i("Jackfruit", IngredientCategory.FRUIT, "South Asia", 95, "1 cup"),
            i("Passion Fruit", IngredientCategory.FRUIT, "South American", 97, "2 fruits"),
            i("Plum", IngredientCategory.FRUIT, "Global", 46, "2 plums"),
            i("Apricot", IngredientCategory.FRUIT, "Mediterranean", 48, "3 apricots"),
            i("Blackberries", IngredientCategory.FRUIT, "Global", 43, "1 cup"),
            i("Cranberries", IngredientCategory.FRUIT, "North American", 46, "1 cup"),
            i("Starfruit", IngredientCategory.FRUIT, "Southeast Asia", 31, "1 fruit"),
            i("Persimmon", IngredientCategory.FRUIT, "East Asia", 70, "1 fruit"),
            i("Cherries", IngredientCategory.FRUIT, "Global", 63, "1 cup"),
            i("Mulberries", IngredientCategory.FRUIT, "Middle Eastern", 43, "1 cup"),
            i("Rambutan", IngredientCategory.FRUIT, "Southeast Asia", 82, "8 fruits"),
            i("Longan", IngredientCategory.FRUIT, "China", 60, "1 cup"),
            i("Soursop", IngredientCategory.FRUIT, "Caribbean", 66, "1 cup"),

            i("Spinach", IngredientCategory.VEGETABLE, "Global", 23, "1 cup raw"),
            i("Kale", IngredientCategory.VEGETABLE, "Global", 49, "1 cup chopped"),
            i("Broccoli", IngredientCategory.VEGETABLE, "Global", 34, "1 cup"),
            i("Cauliflower", IngredientCategory.VEGETABLE, "Global", 25, "1 cup"),
            i("Carrot", IngredientCategory.VEGETABLE, "Global", 41, "1 medium carrot"),
            i("Beetroot", IngredientCategory.VEGETABLE, "Global", 43, "1 cup diced"),
            i("Bell Pepper", IngredientCategory.VEGETABLE, "Global", 31, "1 cup sliced"),
            i("Tomato", IngredientCategory.VEGETABLE, "Global", 18, "1 medium tomato"),
            i("Cucumber", IngredientCategory.VEGETABLE, "Global", 15, "1 cup sliced"),
            i("Zucchini", IngredientCategory.VEGETABLE, "Mediterranean", 17, "1 cup sliced"),
            i("Eggplant", IngredientCategory.VEGETABLE, "Mediterranean", 25, "1 cup cubed"),
            i("Okra", IngredientCategory.VEGETABLE, "African", 33, "1 cup"),
            i("Cabbage", IngredientCategory.VEGETABLE, "Global", 25, "1 cup chopped"),
            i("Brussels Sprouts", IngredientCategory.VEGETABLE, "European", 43, "1 cup"),
            i("Asparagus", IngredientCategory.VEGETABLE, "European", 20, "1 cup"),
            i("Lettuce", IngredientCategory.VEGETABLE, "Global", 15, "2 cups"),
            i("Arugula", IngredientCategory.VEGETABLE, "Mediterranean", 25, "2 cups"),
            i("Onion", IngredientCategory.VEGETABLE, "Global", 40, "half onion"),
            i("Garlic", IngredientCategory.VEGETABLE, "Global", 149, "3 cloves"),
            i("Leek", IngredientCategory.VEGETABLE, "European", 61, "1 cup chopped"),
            i("Pumpkin", IngredientCategory.VEGETABLE, "Global", 26, "1 cup cooked"),
            i("Sweet Potato", IngredientCategory.VEGETABLE, "Global", 86, "1 medium"),
            i("Potato", IngredientCategory.VEGETABLE, "Global", 77, "1 medium"),
            i("Yam", IngredientCategory.VEGETABLE, "African", 118, "1 cup"),
            i("Radish", IngredientCategory.VEGETABLE, "Global", 16, "1 cup"),
            i("Turnip", IngredientCategory.VEGETABLE, "European", 28, "1 cup"),
            i("Green Beans", IngredientCategory.VEGETABLE, "Global", 31, "1 cup"),
            i("Peas", IngredientCategory.VEGETABLE, "Global", 81, "1 cup"),
            i("Corn", IngredientCategory.VEGETABLE, "Americas", 86, "1 cup"),
            i("Mushroom", IngredientCategory.VEGETABLE, "Global", 22, "1 cup"),
            i("Bok Choy", IngredientCategory.VEGETABLE, "Chinese", 13, "1 cup"),
            i("Napa Cabbage", IngredientCategory.VEGETABLE, "Chinese", 16, "1 cup"),
            i("Lotus Root", IngredientCategory.VEGETABLE, "East Asia", 74, "1 cup"),
            i("Artichoke", IngredientCategory.VEGETABLE, "Mediterranean", 47, "1 medium"),
            i("Celery", IngredientCategory.VEGETABLE, "Global", 16, "1 cup chopped"),
            i("Bean Sprouts", IngredientCategory.VEGETABLE, "Asian", 31, "1 cup"),

            i("Orange Juice", IngredientCategory.JUICE, "Global", 45, "1 glass"),
            i("Apple Juice", IngredientCategory.JUICE, "Global", 46, "1 glass"),
            i("Carrot Juice", IngredientCategory.JUICE, "Global", 40, "1 glass"),
            i("Beet Juice", IngredientCategory.JUICE, "Global", 43, "1 glass"),
            i("Pomegranate Juice", IngredientCategory.JUICE, "Middle Eastern", 54, "1 glass"),
            i("Mango Juice", IngredientCategory.JUICE, "South Asian", 60, "1 glass"),
            i("Pineapple Juice", IngredientCategory.JUICE, "Tropical", 53, "1 glass"),
            i("Guava Juice", IngredientCategory.JUICE, "Latin American", 56, "1 glass"),
            i("Watermelon Juice", IngredientCategory.JUICE, "Global", 30, "1 glass"),
            i("Cranberry Juice", IngredientCategory.JUICE, "North American", 46, "1 glass"),
            i("Tomato Juice", IngredientCategory.JUICE, "Global", 17, "1 glass"),
            i("Sugarcane Juice", IngredientCategory.JUICE, "South Asian", 74, "1 glass"),
            i("Lemonade", IngredientCategory.JUICE, "Global", 40, "1 glass"),
            i("Coconut Water", IngredientCategory.JUICE, "Tropical", 19, "1 glass"),
            i("Mixed Berry Juice", IngredientCategory.JUICE, "Global", 48, "1 glass"),
            i("Lemon Juice", IngredientCategory.JUICE, "Global", 22, "2 tbsp"),

            i("Almonds Roasted", IngredientCategory.SNACK, "Global", 579, "28 g handful"),
            i("Walnuts", IngredientCategory.SNACK, "Global", 654, "28 g handful"),
            i("Pistachios", IngredientCategory.SNACK, "Middle Eastern", 562, "28 g handful"),
            i("Cashews", IngredientCategory.SNACK, "Global", 553, "28 g handful"),
            i("Trail Mix", IngredientCategory.SNACK, "Global", 462, "30 g pack"),
            i("Popcorn Air Popped", IngredientCategory.SNACK, "North American", 387, "3 cups"),
            i("Potato Chips", IngredientCategory.SNACK, "Global", 536, "30 g pack"),
            i("Nacho Chips", IngredientCategory.SNACK, "Mexican", 498, "30 g pack"),
            i("Pretzels", IngredientCategory.SNACK, "European", 380, "30 g pack"),
            i("Granola Bar", IngredientCategory.SNACK, "Global", 420, "1 bar"),
            i("Dark Chocolate", IngredientCategory.SNACK, "European", 598, "20 g"),
            i("Peanut Butter Cookie", IngredientCategory.SNACK, "Global", 488, "1 cookie"),
            i("Rice Crackers", IngredientCategory.SNACK, "Japanese", 416, "20 g"),
            i("Hummus Dip", IngredientCategory.SNACK, "Middle Eastern", 166, "2 tbsp"),
            i("Yogurt Parfait", IngredientCategory.SNACK, "Global", 115, "1 cup"),
            i("Samosa", IngredientCategory.SNACK, "Indian", 262, "1 piece"),
            i("Spring Roll", IngredientCategory.SNACK, "Asian", 220, "1 piece"),
            i("Empanada", IngredientCategory.SNACK, "Latin American", 330, "1 piece"),
            i("Falafel Ball", IngredientCategory.SNACK, "Middle Eastern", 333, "3 balls"),
            i("Cheese Sticks", IngredientCategory.SNACK, "Global", 320, "1 stick"),
            i("Protein Bar", IngredientCategory.SNACK, "Global", 360, "1 bar"),
            i("Sesame Snaps", IngredientCategory.SNACK, "Middle Eastern", 510, "20 g"),
            i("Plantain Chips", IngredientCategory.SNACK, "Caribbean", 530, "30 g"),
            i("Corn Tortilla Chips", IngredientCategory.SNACK, "Mexican", 490, "30 g"),
            i("Roasted Chickpeas Snack", IngredientCategory.SNACK, "Global", 380, "30 g"),

            i("White Rice Cooked", IngredientCategory.RICE, "Global", 130, "1 cup cooked"),
            i("Brown Rice Cooked", IngredientCategory.RICE, "Global", 112, "1 cup cooked"),
            i("Basmati Rice Cooked", IngredientCategory.RICE, "Indian", 121, "1 cup cooked"),
            i("Jasmine Rice Cooked", IngredientCategory.RICE, "Thai", 129, "1 cup cooked"),
            i("Sushi Rice Cooked", IngredientCategory.RICE, "Japanese", 130, "1 cup cooked"),
            i("Arborio Rice Cooked", IngredientCategory.RICE, "Italian", 130, "1 cup cooked"),
            i("Wild Rice Cooked", IngredientCategory.RICE, "North American", 101, "1 cup cooked"),
            i("Black Rice Cooked", IngredientCategory.RICE, "Asian", 145, "1 cup cooked"),
            i("Red Rice Cooked", IngredientCategory.RICE, "Asian", 111, "1 cup cooked"),
            i("Sticky Rice Cooked", IngredientCategory.RICE, "Southeast Asian", 169, "1 cup cooked"),
            i("Biryani Rice Base", IngredientCategory.RICE, "Indian", 172, "1 cup cooked"),

            i("Chicken Breast Cooked", IngredientCategory.MEAT, "Global", 165, "100 g cooked"),
            i("Chicken Thigh Cooked", IngredientCategory.MEAT, "Global", 209, "100 g cooked"),
            i("Turkey Breast Cooked", IngredientCategory.MEAT, "North American", 135, "100 g cooked"),
            i("Beef Sirloin Cooked", IngredientCategory.MEAT, "Global", 206, "100 g cooked"),
            i("Beef Mince Lean Cooked", IngredientCategory.MEAT, "Global", 217, "100 g cooked"),
            i("Lamb Leg Roasted", IngredientCategory.MEAT, "Middle Eastern", 250, "100 g cooked"),
            i("Pork Loin Cooked", IngredientCategory.MEAT, "Global", 242, "100 g cooked"),
            i("Pork Belly Cooked", IngredientCategory.MEAT, "Asian", 518, "100 g cooked"),
            i("Goat Meat Cooked", IngredientCategory.MEAT, "African", 143, "100 g cooked"),
            i("Duck Breast Roasted", IngredientCategory.MEAT, "French", 337, "100 g cooked"),
            i("Ham Lean", IngredientCategory.MEAT, "European", 145, "100 g"),
            i("Bacon Crispy", IngredientCategory.MEAT, "Global", 541, "2 slices"),
            i("Veal Cutlet Cooked", IngredientCategory.MEAT, "Italian", 172, "100 g cooked"),
            i("Rabbit Meat Cooked", IngredientCategory.MEAT, "European", 173, "100 g cooked"),
            i("Sausage Pork", IngredientCategory.MEAT, "Global", 301, "1 sausage"),
            i("Chorizo", IngredientCategory.MEAT, "Spanish", 455, "1 link"),
            i("Beef Meatballs", IngredientCategory.MEAT, "Italian", 286, "4 meatballs"),
            i("Chicken Sausage", IngredientCategory.MEAT, "Global", 230, "1 sausage"),
            i("Ground Turkey Cooked", IngredientCategory.MEAT, "North American", 203, "100 g cooked"),
            i("Bison Steak Cooked", IngredientCategory.MEAT, "North American", 146, "100 g cooked"),
            i("Venison Cooked", IngredientCategory.MEAT, "Nordic", 158, "100 g cooked"),
            i("Mutton Curry Cut Cooked", IngredientCategory.MEAT, "Indian", 294, "100 g cooked"),
            i("Chicken Liver Cooked", IngredientCategory.MEAT, "Global", 167, "100 g cooked"),
            i("Beef Liver Cooked", IngredientCategory.MEAT, "Global", 175, "100 g cooked"),
            i("Jerky Beef", IngredientCategory.MEAT, "North American", 410, "30 g"),
            i("Prosciutto", IngredientCategory.MEAT, "Italian", 247, "30 g"),
            i("Corned Beef", IngredientCategory.MEAT, "Irish", 251, "100 g"),
            i("Salami", IngredientCategory.MEAT, "European", 407, "30 g"),
            i("Meatloaf Slice", IngredientCategory.MEAT, "North American", 250, "1 slice"),
            i("Roast Beef", IngredientCategory.MEAT, "Global", 217, "100 g"),

            i("Salmon Fillet Cooked", IngredientCategory.SEAFOOD, "Global", 208, "100 g cooked"),
            i("Tuna Fresh Cooked", IngredientCategory.SEAFOOD, "Global", 132, "100 g cooked"),
            i("Sardines", IngredientCategory.SEAFOOD, "Mediterranean", 208, "100 g"),
            i("Mackerel Cooked", IngredientCategory.SEAFOOD, "Global", 262, "100 g cooked"),
            i("Shrimp Cooked", IngredientCategory.SEAFOOD, "Global", 99, "100 g cooked"),
            i("Prawns Cooked", IngredientCategory.SEAFOOD, "Global", 99, "100 g cooked"),
            i("Crab Cooked", IngredientCategory.SEAFOOD, "Global", 97, "100 g cooked"),
            i("Lobster Cooked", IngredientCategory.SEAFOOD, "Global", 89, "100 g cooked"),
            i("Mussels Cooked", IngredientCategory.SEAFOOD, "Mediterranean", 172, "100 g cooked"),
            i("Clams Cooked", IngredientCategory.SEAFOOD, "Mediterranean", 148, "100 g cooked"),
            i("Oysters Cooked", IngredientCategory.SEAFOOD, "Global", 81, "100 g cooked"),
            i("Squid Cooked", IngredientCategory.SEAFOOD, "Mediterranean", 92, "100 g cooked"),
            i("Octopus Cooked", IngredientCategory.SEAFOOD, "Mediterranean", 82, "100 g cooked"),
            i("Cod Cooked", IngredientCategory.SEAFOOD, "Global", 105, "100 g cooked"),
            i("Haddock Cooked", IngredientCategory.SEAFOOD, "Global", 90, "100 g cooked"),
            i("Tilapia Cooked", IngredientCategory.SEAFOOD, "Global", 129, "100 g cooked"),
            i("Snapper Cooked", IngredientCategory.SEAFOOD, "Caribbean", 128, "100 g cooked"),
            i("Sea Bass Cooked", IngredientCategory.SEAFOOD, "Mediterranean", 124, "100 g cooked"),
            i("Anchovies", IngredientCategory.SEAFOOD, "Mediterranean", 210, "100 g"),
            i("Scallops Cooked", IngredientCategory.SEAFOOD, "Global", 111, "100 g cooked"),
            i("Catfish Cooked", IngredientCategory.SEAFOOD, "North American", 122, "100 g cooked"),
            i("Trout Cooked", IngredientCategory.SEAFOOD, "Nordic", 168, "100 g cooked"),
            i("Eel Cooked", IngredientCategory.SEAFOOD, "Japanese", 236, "100 g cooked"),
            i("Pollock Cooked", IngredientCategory.SEAFOOD, "Global", 92, "100 g cooked"),
            i("Herring Cooked", IngredientCategory.SEAFOOD, "Nordic", 217, "100 g cooked"),

            i("Chickpeas Cooked", IngredientCategory.LEGUME, "Middle Eastern", 164, "1 cup cooked"),
            i("Lentils Cooked", IngredientCategory.LEGUME, "South Asian", 116, "1 cup cooked"),
            i("Black Beans Cooked", IngredientCategory.LEGUME, "Latin American", 132, "1 cup cooked"),
            i("Kidney Beans Cooked", IngredientCategory.LEGUME, "Global", 127, "1 cup cooked"),
            i("Tofu Firm", IngredientCategory.LEGUME, "East Asian", 144, "100 g"),
            i("Paneer", IngredientCategory.DAIRY, "Indian", 265, "100 g"),
            i("Greek Yogurt", IngredientCategory.DAIRY, "Greek", 59, "100 g"),
            i("Milk Whole", IngredientCategory.DAIRY, "Global", 61, "1 cup"),
            i("Olive Oil", IngredientCategory.OIL, "Mediterranean", 884, "1 tbsp"),
            i("Butter Unsalted", IngredientCategory.OIL, "Global", 717, "1 tbsp"),
            i("Coconut Milk", IngredientCategory.DAIRY, "Thai", 230, "100 ml"),
            i("Wheat Flour", IngredientCategory.GRAIN, "Global", 364, "100 g"),
            i("Spaghetti Cooked", IngredientCategory.GRAIN, "Italian", 158, "1 cup cooked"),
            i("Whole Wheat Pasta Cooked", IngredientCategory.GRAIN, "Italian", 149, "1 cup cooked"),
            i("Ramen Noodles Cooked", IngredientCategory.GRAIN, "Japanese", 138, "1 cup cooked"),
            i("Quinoa Cooked", IngredientCategory.GRAIN, "South American", 120, "1 cup cooked"),
            i("Couscous Cooked", IngredientCategory.GRAIN, "North African", 112, "1 cup cooked"),
            i("Oats Dry", IngredientCategory.GRAIN, "Global", 389, "half cup dry"),
            i("Dosa Batter Fermented", IngredientCategory.GRAIN, "South Indian", 150, "1 dosa (30 g)"),
            i("Dosa Plain", IngredientCategory.GRAIN, "South Indian", 168, "1 dosa (90 g)"),
            i("Idli Steamed", IngredientCategory.GRAIN, "South Indian", 146, "1 idli (50 g)"),
            i("Idiyappam", IngredientCategory.GRAIN, "South Indian", 159, "1 nest (60 g)"),
            i("Waffle Plain", IngredientCategory.GRAIN, "Western", 291, "1 waffle (75 g)"),
            i("Pancake Plain", IngredientCategory.GRAIN, "Western", 227, "1 pancake (60 g)"),
            i("Scrambled Eggs", IngredientCategory.OTHER, "Western", 148, "1 serving (100 g)"),
            i("Bacon Strip Cooked", IngredientCategory.MEAT, "Western", 541, "1 strip (12 g)"),
            i("Soy Sauce", IngredientCategory.SAUCE, "Asian", 53, "1 tbsp"),
            i("Maple Syrup", IngredientCategory.SAUCE, "North American", 260, "1 tbsp (20 g)"),
            i("Fish Sauce", IngredientCategory.SAUCE, "Southeast Asian", 35, "1 tbsp"),
            i("Tamarind Pulp", IngredientCategory.SAUCE, "Indian", 239, "1 tbsp"),
            i("Curry Powder", IngredientCategory.SPICE, "Indian", 325, "1 tbsp"),
            i("Garam Masala", IngredientCategory.SPICE, "Indian", 379, "1 tbsp"),
            i("Turmeric Powder", IngredientCategory.SPICE, "Indian", 354, "1 tbsp"),
            i("Cumin Powder", IngredientCategory.SPICE, "Middle Eastern", 375, "1 tbsp"),
            i("Paprika", IngredientCategory.SPICE, "Hungarian", 282, "1 tbsp"),
            i("Mozzarella", IngredientCategory.DAIRY, "Italian", 280, "30 g"),
            i("Feta Cheese", IngredientCategory.DAIRY, "Greek", 264, "30 g"),
            i("Corn Tortilla", IngredientCategory.GRAIN, "Mexican", 218, "1 tortilla"),
            i("Rice Noodles Cooked", IngredientCategory.GRAIN, "Southeast Asian", 109, "1 cup cooked"),
            i("Egg Whole", IngredientCategory.OTHER, "Global", 143, "1 egg"),
            i("Nori Seaweed", IngredientCategory.OTHER, "Japanese", 35, "1 sheet"),

            i("Sunflower Oil", IngredientCategory.OIL, "Global", 884, "1 tbsp"),
            i("Mustard Oil", IngredientCategory.OIL, "Indian", 884, "1 tbsp"),
            i("Sesame Oil", IngredientCategory.OIL, "Asian", 884, "1 tbsp"),
            i("Groundnut Oil", IngredientCategory.OIL, "Indian", 884, "1 tbsp"),
            i("Canola Oil", IngredientCategory.OIL, "Western", 884, "1 tbsp"),
            i("Palm Oil", IngredientCategory.OIL, "African", 884, "1 tbsp"),
            i("Rice Bran Oil", IngredientCategory.OIL, "Asian", 884, "1 tbsp"),
            i("Avocado Oil", IngredientCategory.OIL, "Global", 884, "1 tbsp"),
            i("Ghee Clarified Butter", IngredientCategory.OIL, "Indian", 900, "1 tbsp"),
            i("Coconut Oil", IngredientCategory.OIL, "Tropical", 892, "1 tbsp"),
            i("Soybean Oil", IngredientCategory.OIL, "Global", 884, "1 tbsp"),
            i("Corn Oil", IngredientCategory.OIL, "Global", 884, "1 tbsp"),
            i("Flaxseed Oil", IngredientCategory.OIL, "Global", 884, "1 tbsp"),
            i("Walnut Oil", IngredientCategory.OIL, "Mediterranean", 884, "1 tbsp"),

            i("Skim Milk", IngredientCategory.DAIRY, "Global", 34, "1 cup"),
            i("Buttermilk", IngredientCategory.DAIRY, "Indian", 62, "1 cup"),
            i("Curd", IngredientCategory.DAIRY, "Indian", 61, "1 cup"),
            i("Paneer Low Fat", IngredientCategory.DAIRY, "Indian", 208, "100 g"),
            i("Cheddar Cheese", IngredientCategory.DAIRY, "Western", 403, "30 g"),
            i("Parmesan Cheese", IngredientCategory.DAIRY, "Italian", 431, "20 g"),
            i("Cream Cheese", IngredientCategory.DAIRY, "Western", 342, "30 g"),
            i("Cottage Cheese", IngredientCategory.DAIRY, "Global", 98, "100 g"),
            i("Whipping Cream", IngredientCategory.DAIRY, "Global", 340, "100 ml"),
            i("Condensed Milk", IngredientCategory.DAIRY, "Global", 321, "2 tbsp"),
            i("Evaporated Milk", IngredientCategory.DAIRY, "Global", 134, "100 ml"),
            i("Frozen Yogurt", IngredientCategory.DAIRY, "Western", 159, "100 g"),
            i("Vanilla Ice Cream", IngredientCategory.DAIRY, "Global", 207, "100 g"),
            i("Chocolate Ice Cream", IngredientCategory.DAIRY, "Global", 216, "100 g"),
            i("Strawberry Ice Cream", IngredientCategory.DAIRY, "Global", 192, "100 g"),
            i("Mango Ice Cream", IngredientCategory.DAIRY, "Indian", 200, "100 g"),
            i("Pistachio Ice Cream", IngredientCategory.DAIRY, "Middle Eastern", 220, "100 g"),
            i("Kulfi", IngredientCategory.DAIRY, "Indian", 260, "100 g"),
            i("Gelato", IngredientCategory.DAIRY, "Italian", 180, "100 g"),

            i("Plain Cake Sponge", IngredientCategory.SNACK, "Global", 297, "1 slice"),
            i("Chocolate Cake", IngredientCategory.SNACK, "Western", 371, "1 slice"),
            i("Black Forest Cake", IngredientCategory.SNACK, "European", 280, "1 slice"),
            i("Red Velvet Cake", IngredientCategory.SNACK, "Western", 360, "1 slice"),
            i("Cheesecake", IngredientCategory.SNACK, "Western", 321, "1 slice"),
            i("Carrot Cake", IngredientCategory.SNACK, "Western", 415, "1 slice"),
            i("Brownie", IngredientCategory.SNACK, "Western", 466, "1 piece"),
            i("Cupcake Vanilla", IngredientCategory.SNACK, "Global", 305, "1 cupcake"),
            i("Tiramisu", IngredientCategory.SNACK, "Italian", 283, "1 serving"),

            i("Vada Pav", IngredientCategory.SNACK, "Indian", 290, "1 piece"),
            i("Mixture Namkeen", IngredientCategory.SNACK, "Indian", 520, "30 g"),
            i("Bhel Puri", IngredientCategory.SNACK, "Indian", 220, "1 bowl"),
            i("Dhokla", IngredientCategory.SNACK, "Indian", 160, "1 piece"),
            i("Kachori", IngredientCategory.SNACK, "Indian", 280, "1 piece"),

            i("Veg Soup Base", IngredientCategory.OTHER, "Global", 35, "100 g"),
            i("Chicken Soup Base", IngredientCategory.MEAT, "Global", 55, "100 g"),
            i("Mutton Soup Base", IngredientCategory.MEAT, "Indian", 75, "100 g"),
            i("Seafood Soup Base", IngredientCategory.SEAFOOD, "Asian", 68, "100 g"),
            i("Sweet Corn Kernels", IngredientCategory.VEGETABLE, "Global", 86, "100 g"),
            i("Spring Onion", IngredientCategory.VEGETABLE, "Asian", 32, "100 g"),
            i("Chicken Mince Cooked", IngredientCategory.MEAT, "Global", 210, "100 g"),
            i("Chicken Wings Cooked", IngredientCategory.MEAT, "Global", 254, "100 g"),
            i("Mutton Mince Cooked", IngredientCategory.MEAT, "Indian", 282, "100 g"),
            i("Turkey Mince Cooked", IngredientCategory.MEAT, "Western", 203, "100 g"),
            i("Salami Chicken", IngredientCategory.MEAT, "Global", 280, "30 g"),
            i("Ham Turkey", IngredientCategory.MEAT, "Western", 124, "30 g"),
            i("Fish Fillet Battered", IngredientCategory.SEAFOOD, "Western", 232, "100 g")
        );
    }

    public static List<DishSeed> dishes() {
        return List.of(
            d("Chicken Biryani", "Indian", "Spiced rice with chicken and yogurt", c("Basmati Rice Cooked", 180), c("Chicken Thigh Cooked", 130), c("Onion", 40), c("Greek Yogurt", 35), c("Olive Oil", 10), c("Curry Powder", 6)),
            d("Sushi Salmon Bowl", "Japanese", "Sushi rice bowl with salmon and avocado", c("Sushi Rice Cooked", 170), c("Salmon Fillet Cooked", 110), c("Cucumber", 40), c("Avocado", 50), c("Soy Sauce", 10), c("Nori Seaweed", 3)),
            d("Shrimp Paella", "Spanish", "Rice and shrimp with Mediterranean vegetables", c("Arborio Rice Cooked", 180), c("Shrimp Cooked", 120), c("Bell Pepper", 50), c("Tomato", 70), c("Olive Oil", 10)),
            d("Jollof Chicken Rice", "West African", "Tomato rice with chicken", c("White Rice Cooked", 180), c("Chicken Thigh Cooked", 120), c("Tomato", 90), c("Onion", 45), c("Olive Oil", 8)),
            d("Chicken Shawarma Plate", "Middle Eastern", "Chicken with salad and hummus", c("Chicken Breast Cooked", 150), c("Lettuce", 60), c("Tomato", 70), c("Cucumber", 60), c("Hummus Dip", 70)),
            d("Beef Tacos", "Mexican", "Ground beef tacos with fresh vegetables", c("Beef Mince Lean Cooked", 130), c("Corn Tortilla", 100), c("Tomato", 50), c("Onion", 40), c("Lettuce", 40)),
            d("Pho Beef Bowl", "Vietnamese", "Noodle broth style bowl with beef", c("Ramen Noodles Cooked", 190), c("Beef Sirloin Cooked", 110), c("Onion", 45), c("Bok Choy", 60), c("Soy Sauce", 8)),
            d("Greek Salad Bowl", "Greek", "Classic cucumber tomato feta salad", c("Tomato", 120), c("Cucumber", 100), c("Onion", 35), c("Feta Cheese", 45), c("Olive Oil", 10)),
            d("Thai Seafood Pad Thai", "Thai", "Rice noodles with shrimp and egg", c("Rice Noodles Cooked", 180), c("Shrimp Cooked", 100), c("Bean Sprouts", 70), c("Egg Whole", 55), c("Fish Sauce", 10)),
            d("Butter Chicken Rice", "Indian", "Creamy chicken curry with rice", c("Chicken Thigh Cooked", 140), c("Basmati Rice Cooked", 170), c("Tomato", 90), c("Butter Unsalted", 12), c("Greek Yogurt", 50)),
            d("Tuna Poke Bowl", "Hawaiian", "Fresh tuna and rice bowl", c("Sushi Rice Cooked", 170), c("Tuna Fresh Cooked", 120), c("Avocado", 50), c("Cucumber", 45), c("Soy Sauce", 10)),
            d("Salmon Teriyaki Rice", "Japanese", "Salmon with jasmine rice and broccoli", c("Salmon Fillet Cooked", 130), c("Jasmine Rice Cooked", 170), c("Broccoli", 70), c("Soy Sauce", 12)),
            d("Falafel Wrap Plate", "Middle Eastern", "Falafel with crunchy salad and hummus", c("Falafel Ball", 130), c("Lettuce", 60), c("Tomato", 60), c("Cucumber", 60), c("Hummus Dip", 70)),
            d("Tofu Veg Stir Fry", "Chinese", "Tofu and vegetables with soy and rice", c("Tofu Firm", 130), c("Broccoli", 80), c("Carrot", 70), c("Bell Pepper", 70), c("Soy Sauce", 10), c("White Rice Cooked", 150)),
            d("Moroccan Lamb Couscous", "Moroccan", "Lamb and chickpea couscous", c("Lamb Leg Roasted", 120), c("Couscous Cooked", 180), c("Carrot", 60), c("Chickpeas Cooked", 70), c("Olive Oil", 8)),
            d("Brazilian Feijoada Bowl", "Brazilian", "Black beans and pork over rice", c("Black Beans Cooked", 150), c("Pork Loin Cooked", 110), c("White Rice Cooked", 170), c("Onion", 40)),
            d("Korean Beef Rice Bowl", "Korean", "Beef, cabbage and rice bowl", c("Beef Sirloin Cooked", 120), c("White Rice Cooked", 170), c("Cabbage", 70), c("Soy Sauce", 12)),
            d("Turkish Doner Plate", "Turkish", "Lamb with cool yogurt salad", c("Lamb Leg Roasted", 130), c("Tomato", 70), c("Onion", 40), c("Lettuce", 60), c("Greek Yogurt", 60)),
            d("Seafood Pasta Mediterranean", "Mediterranean", "Pasta with shrimp and mussels", c("Spaghetti Cooked", 190), c("Shrimp Cooked", 90), c("Mussels Cooked", 90), c("Tomato", 80), c("Olive Oil", 9)),
            d("Egg Fried Rice", "Chinese", "Classic egg fried rice", c("White Rice Cooked", 180), c("Egg Whole", 100), c("Peas", 60), c("Carrot", 50), c("Soy Sauce", 10)),
            d("American Beef Burger Bowl", "American", "Burger flavors without bun", c("Beef Mince Lean Cooked", 140), c("Lettuce", 70), c("Tomato", 70), c("Onion", 50), c("Potato", 130)),
            d("Filipino Chicken Adobo Bowl", "Filipino", "Savory chicken and rice", c("Chicken Thigh Cooked", 140), c("White Rice Cooked", 170), c("Soy Sauce", 14), c("Garlic", 10)),
            d("Cajun Seafood Rice", "Louisiana", "Spiced seafood rice with peppers", c("White Rice Cooked", 170), c("Shrimp Cooked", 100), c("Catfish Cooked", 100), c("Bell Pepper", 60), c("Onion", 40)),
            d("Ethiopian Lentil Stew Plate", "Ethiopian", "Lentils with tomatoes and rice", c("Lentils Cooked", 190), c("Onion", 60), c("Tomato", 80), c("White Rice Cooked", 150), c("Olive Oil", 8)),
            d("Nigerian Suya Beef Bowl", "Nigerian", "Beef and rice with warm spices", c("Beef Sirloin Cooked", 130), c("White Rice Cooked", 160), c("Onion", 45), c("Tomato", 60), c("Paprika", 4)),
            d("Thai Green Curry Seafood", "Thai", "Seafood coconut curry with rice", c("Coconut Milk", 120), c("Shrimp Cooked", 100), c("Cod Cooked", 100), c("Jasmine Rice Cooked", 150), c("Eggplant", 70)),
            d("Peruvian Ceviche Rice Plate", "Peruvian", "Citrus fish plate with rice", c("Tilapia Cooked", 120), c("White Rice Cooked", 150), c("Onion", 50), c("Tomato", 50), c("Lemon Juice", 20)),
            d("Russian Beef Stroganoff Rice", "Russian", "Beef and mushroom creamy rice", c("Beef Sirloin Cooked", 120), c("Mushroom", 80), c("Onion", 50), c("Greek Yogurt", 70), c("Brown Rice Cooked", 160)),
            d("Caribbean Jerk Chicken Bowl", "Caribbean", "Spiced chicken with pineapple rice", c("Chicken Thigh Cooked", 130), c("Brown Rice Cooked", 170), c("Pineapple", 70), c("Bell Pepper", 60)),
            d("Japanese Seafood Ramen", "Japanese", "Ramen with shrimp and squid", c("Ramen Noodles Cooked", 190), c("Shrimp Cooked", 80), c("Squid Cooked", 80), c("Bok Choy", 70), c("Soy Sauce", 10)),
            d("Veg Quinoa Power Bowl", "Global", "Quinoa bowl with greens and chickpeas", c("Quinoa Cooked", 180), c("Chickpeas Cooked", 110), c("Spinach", 70), c("Cucumber", 60), c("Avocado", 50)),
            d("Mediterranean Veggie Plate", "Mediterranean", "Hummus with fresh crunchy vegetables", c("Hummus Dip", 90), c("Tomato", 90), c("Cucumber", 90), c("Bell Pepper", 80), c("Olive Oil", 8)),

            d("Mumbai Vada Pav Plate", "Indian", "Spiced potato snack bun from western India", c("Vada Pav", 180), c("Onion", 25), c("Tomato", 25), c("Mustard Oil", 8)),
            d("Indian Mixture Snack Bowl", "Indian", "Crispy namkeen mix with onions and lemon", c("Mixture Namkeen", 100), c("Onion", 20), c("Tomato", 20), c("Lemon Juice", 10)),
            d("Veg Sweet Corn Soup", "Indo Chinese", "Vegetarian sweet corn soup", c("Veg Soup Base", 220), c("Sweet Corn Kernels", 100), c("Carrot", 40), c("Spring Onion", 20), c("Soy Sauce", 6)),
            d("Hot And Sour Veg Soup", "Indo Chinese", "Tangy vegetable soup with cabbage", c("Veg Soup Base", 240), c("Cabbage", 80), c("Carrot", 50), c("Mushroom", 60), c("Soy Sauce", 8)),
            d("Chicken Clear Soup", "Chinese", "Light chicken broth soup", c("Chicken Soup Base", 260), c("Chicken Breast Cooked", 90), c("Spring Onion", 20), c("Soy Sauce", 6)),
            d("Chicken Manchow Soup", "Indo Chinese", "Savory chicken soup with vegetables", c("Chicken Soup Base", 240), c("Chicken Mince Cooked", 90), c("Cabbage", 60), c("Carrot", 40), c("Soy Sauce", 7)),
            d("Mutton Pepper Soup", "Indian", "Spiced mutton stock soup", c("Mutton Soup Base", 250), c("Mutton Mince Cooked", 90), c("Onion", 30), c("Paprika", 3)),
            d("Seafood Clear Soup", "Eastern", "Seafood broth with spring onion", c("Seafood Soup Base", 260), c("Shrimp Cooked", 80), c("Mussels Cooked", 60), c("Spring Onion", 20)),
            d("Tomato Basil Soup Veg", "European", "Classic tomato basil soup", c("Veg Soup Base", 240), c("Tomato", 120), c("Olive Oil", 8), c("Garlic", 8)),
            d("Mediterranean Lentil Soup", "Mediterranean", "Lentils with vegetables and olive oil", c("Lentils Cooked", 180), c("Tomato", 70), c("Carrot", 60), c("Olive Oil", 8), c("Onion", 40)),
            d("African Peanut Chicken Stew", "African", "West African style chicken and peanut base", c("Chicken Thigh Cooked", 140), c("Tomato", 90), c("Onion", 50), c("Groundnut Oil", 10), c("Sweet Potato", 120)),
            d("Western Grilled Chicken Salad", "Western", "Lean grilled chicken with greens", c("Chicken Breast Cooked", 150), c("Lettuce", 80), c("Cucumber", 60), c("Tomato", 60), c("Olive Oil", 8)),
            d("European Beef And Potatoes", "European", "Beef sirloin with potatoes and onions", c("Beef Sirloin Cooked", 150), c("Potato", 180), c("Onion", 50), c("Canola Oil", 8)),
            d("Southern Veg Rice Bowl", "Southern", "Vegetable-heavy rice bowl", c("Brown Rice Cooked", 170), c("Carrot", 70), c("Peas", 70), c("Broccoli", 80), c("Olive Oil", 7)),
            d("Northern Protein Plate", "Northern", "High-protein mixed meat and greens", c("Turkey Breast Cooked", 130), c("Chicken Breast Cooked", 120), c("Cabbage", 80), c("Onion", 40), c("Sunflower Oil", 8)),
            d("Eastern Seafood Rice", "Eastern", "Rice with mixed seafood and soy notes", c("Jasmine Rice Cooked", 170), c("Shrimp Cooked", 90), c("Squid Cooked", 80), c("Soy Sauce", 9), c("Spring Onion", 25)),
            d("Chinese Chicken Fried Rice", "Chinese", "Classic chicken fried rice", c("White Rice Cooked", 180), c("Chicken Mince Cooked", 90), c("Egg Whole", 60), c("Carrot", 50), c("Soy Sauce", 8)),
            d("Indo Chinese Hakka Noodles", "Indo Chinese", "Stir-fried noodles with vegetables", c("Ramen Noodles Cooked", 190), c("Cabbage", 70), c("Carrot", 60), c("Spring Onion", 25), c("Soy Sauce", 10), c("Sesame Oil", 6)),
            d("Chicken Noodles", "Indo Chinese", "Classic street-style chicken noodles", c("Ramen Noodles Cooked", 200), c("Chicken Breast Cooked", 120), c("Cabbage", 70), c("Carrot", 60), c("Spring Onion", 28), c("Soy Sauce", 10), c("Sesame Oil", 6)),
            d("Chicken Hakka Noodles", "Indo Chinese", "Chicken hakka noodles with crunchy vegetables", c("Ramen Noodles Cooked", 200), c("Chicken Mince Cooked", 120), c("Cabbage", 75), c("Carrot", 60), c("Spring Onion", 28), c("Soy Sauce", 10), c("Sesame Oil", 6)),
            d("Chicken Chow Mein", "Chinese", "Stir-fried chicken chow mein noodles", c("Ramen Noodles Cooked", 195), c("Chicken Breast Cooked", 120), c("Cabbage", 70), c("Carrot", 55), c("Spring Onion", 25), c("Soy Sauce", 10), c("Sesame Oil", 6)),
            d("Chilli Chicken", "Indo Chinese", "Popular Indo Chinese chilli chicken", c("Chicken Thigh Cooked", 170), c("Bell Pepper", 90), c("Onion", 70), c("Soy Sauce", 12), c("Sesame Oil", 8), c("Garlic", 10)),
            d("Chili Chicken", "Indo Chinese", "Regional spelling variant of chilli chicken", c("Chicken Thigh Cooked", 170), c("Bell Pepper", 90), c("Onion", 70), c("Soy Sauce", 12), c("Sesame Oil", 8), c("Garlic", 10)),
            d("Chicken Chilli Gravy", "Indo Chinese", "Chicken chilli gravy with onion and peppers", c("Chicken Thigh Cooked", 165), c("Bell Pepper", 95), c("Onion", 80), c("Chicken Soup Base", 120), c("Soy Sauce", 12), c("Sesame Oil", 8), c("Garlic", 10)),
            d("Mediterranean Fish Plate", "Mediterranean", "Pan fish with vegetables and olive oil", c("Sea Bass Cooked", 140), c("Tomato", 80), c("Cucumber", 70), c("Olive Oil", 9), c("Lemon Juice", 12)),
            d("Indian Chicken Soup Bowl", "Indian", "Comfort chicken soup with spices", c("Chicken Soup Base", 260), c("Chicken Breast Cooked", 100), c("Carrot", 50), c("Onion", 45), c("Garam Masala", 3)),

            d("Curd Rice", "Indian", "Creamy rice with curd and mild tempering", c("Basmati Rice Cooked", 220), c("Curd", 140), c("Mustard Oil", 5), c("Cumin Powder", 2), c("Onion", 20)),
            d("Lemon Rice", "Indian", "Tangy rice tempered with lemon and spices", c("Basmati Rice Cooked", 220), c("Lemon Juice", 28), c("Mustard Oil", 7), c("Curry Powder", 4), c("Cashews", 18)),
            d("Tomato Rice", "Indian", "Tomato-spiced rice with onion", c("Basmati Rice Cooked", 220), c("Tomato", 140), c("Onion", 50), c("Mustard Oil", 7), c("Garam Masala", 3)),
            d("Tamarind Rice", "Indian", "South Indian tamarind-flavored rice", c("Basmati Rice Cooked", 220), c("Tamarind Pulp", 28), c("Mustard Oil", 7), c("Curry Powder", 3), c("Cashews", 15)),
            d("Coconut Rice", "Indian", "Fragrant rice with coconut and spices", c("Basmati Rice Cooked", 210), c("Coconut Flesh", 50), c("Mustard Oil", 6), c("Curry Powder", 3), c("Cashews", 18)),
            d("Jeera Rice", "Indian", "Cumin rice with light ghee finish", c("Basmati Rice Cooked", 220), c("Cumin Powder", 4), c("Ghee Clarified Butter", 8), c("Onion", 25)),
            d("Vegetable Pulao", "Indian", "Classic mixed vegetable pulao", c("Basmati Rice Cooked", 220), c("Carrot", 70), c("Peas", 70), c("Green Beans", 60), c("Onion", 45), c("Mustard Oil", 7)),
            d("Vegetable Pulav", "Indian", "Vegetable pulav variant spelling", c("Basmati Rice Cooked", 220), c("Carrot", 65), c("Peas", 70), c("Green Beans", 60), c("Onion", 45), c("Mustard Oil", 7)),
            d("Peas Pulao", "Indian", "Rice with green peas and aromatic spices", c("Basmati Rice Cooked", 220), c("Peas", 120), c("Onion", 45), c("Ghee Clarified Butter", 7)),
            d("Mushroom Pulao", "Indian", "Mushroom pulao with warm spices", c("Basmati Rice Cooked", 220), c("Mushroom", 120), c("Onion", 50), c("Ghee Clarified Butter", 7), c("Garam Masala", 3)),
            d("Paneer Pulao", "Indian", "Paneer-rich pulao with peas", c("Basmati Rice Cooked", 210), c("Paneer", 90), c("Peas", 65), c("Onion", 45), c("Ghee Clarified Butter", 8)),
            d("Chicken Pulao", "Indian", "Chicken pulao with aromatic rice", c("Basmati Rice Cooked", 210), c("Chicken Thigh Cooked", 130), c("Onion", 50), c("Ghee Clarified Butter", 8), c("Curry Powder", 4)),
            d("Chicken Pulav", "Indian", "Chicken pulav regional spelling", c("Basmati Rice Cooked", 210), c("Chicken Thigh Cooked", 130), c("Onion", 50), c("Ghee Clarified Butter", 8), c("Garam Masala", 4)),
            d("Mutton Pulao", "Indian", "Mutton pulao with rich spices", c("Basmati Rice Cooked", 210), c("Mutton Curry Cut Cooked", 120), c("Onion", 55), c("Ghee Clarified Butter", 9), c("Garam Masala", 4)),
            d("Sambar Rice", "Indian", "Lentil and rice comfort bowl", c("Basmati Rice Cooked", 200), c("Lentils Cooked", 140), c("Tomato", 90), c("Onion", 60), c("Curry Powder", 4), c("Mustard Oil", 5)),
            d("Rasam Rice", "Indian", "Peppery tomato rasam style rice", c("Basmati Rice Cooked", 210), c("Tomato", 130), c("Lemon Juice", 22), c("Cumin Powder", 3), c("Garlic", 8), c("Curry Powder", 2)),
            d("South Indian Veg Thali", "Indian", "Balanced vegetarian thali meal plate", c("White Rice Cooked", 180), c("Lentils Cooked", 130), c("Spinach", 80), c("Curd", 100), c("Potato", 90)),
            d("South Indian Non Veg Thali", "Indian", "Traditional non-veg thali meal plate", c("White Rice Cooked", 180), c("Chicken Thigh Cooked", 150), c("Lentils Cooked", 90), c("Curd", 80), c("Onion", 45)),
            d("Veg Meals Plate", "Indian", "Daily style veg meals with rice and lentils", c("Brown Rice Cooked", 170), c("Lentils Cooked", 130), c("Carrot", 70), c("Peas", 70), c("Curd", 90)),
            d("Non Veg Meals Plate", "Indian", "Daily style non-veg meals with rice and chicken", c("White Rice Cooked", 170), c("Chicken Breast Cooked", 150), c("Lentils Cooked", 90), c("Onion", 50), c("Curd", 70)),

            d("Plain Dosa", "South Indian", "Crispy fermented rice-lentil dosa", c("Dosa Batter Fermented", 120), c("Groundnut Oil", 6)),
            d("Masala Dosa", "South Indian", "Dosa with potato masala filling", c("Dosa Batter Fermented", 130), c("Potato", 140), c("Onion", 45), c("Mustard Oil", 6)),
            d("Steamed Idli Plate", "South Indian", "Soft steamed idli breakfast plate", c("Idli Steamed", 200), c("Lentils Cooked", 100), c("Tomato", 80), c("Onion", 35), c("Curry Powder", 3)),
            d("Idiyappam Coconut Bowl", "South Indian", "String hoppers with coconut milk", c("Idiyappam", 220), c("Coconut Milk", 90), c("Coconut Flesh", 30)),
            d("Waffle Plate", "Western", "Waffles with butter and syrup", c("Waffle Plain", 170), c("Butter Unsalted", 8), c("Maple Syrup", 24)),
            d("Pancake Stack", "Western", "Classic pancakes with syrup", c("Pancake Plain", 190), c("Butter Unsalted", 8), c("Maple Syrup", 24)),
            d("Scrambled Eggs Plate", "Western", "Creamy scrambled eggs breakfast", c("Scrambled Eggs", 180), c("Butter Unsalted", 6), c("Tomato", 50)),
            d("Bacon And Eggs Breakfast", "European", "Scrambled eggs with crispy bacon", c("Scrambled Eggs", 180), c("Bacon Strip Cooked", 36), c("Tomato", 50))
        );
    }

    private static IngredientSeed i(
        String name,
        IngredientCategory category,
        String cuisine,
        double caloriesPer100g,
        String servingNote
    ) {
        return new IngredientSeed(name, category, cuisine, caloriesPer100g, servingNote);
    }

    private static DishComponentSeed c(String ingredientName, double grams) {
        return new DishComponentSeed(ingredientName, grams);
    }

    private static DishSeed d(String name, String cuisine, String description, DishComponentSeed... components) {
        return new DishSeed(name, cuisine, description, List.of(components));
    }
}
